Models/ErrorViewModel.cs
namespace dotnet_mvc_first_app.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;

namespace dotnet_mvc_first_app.Controllers
{
    public class BlogController : Controller
    {
        [Route("my-blog")]
        public IActionResult Index()
        {
            return View();
        }
    }
}
 

Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace dotnet_mvc_first_app.Controllers
{
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using dotnet_mvc_first_app.Models;
using Microsoft.AspNetCore.Mvc;

namespace dotnet_mvc_first_app.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace dotnet_mvc_first_app.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;

namespace dotnet_mvc_first_app.Controllers
{
    public class ProfileController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Blog/Index.cshtml
@{
    ViewData["Title"] = "Blog Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Blog Page</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Dashboard/Index.cshtml
@{
    ViewData["Title"] = "Dashboard";
}

<div class="content-wrapper">
    <section class="content-header">
        <h1>Dashboard</h1>
    </section>
    <section class="content">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Welcome, Naufal!</h3>
            </div>
            <div class="card-body">
                <p>This is my Dashboard.</p>
            </div>
        </div>
    </section>
</div>

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to About Page</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Login/Index.cshtml
@{
    ViewData["Title"] = "Login";
}

<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <b>My</b>App
        </div>
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Sign in to start your session</p>

                <form>
                    <div class="input-group mb-3">
                        <input type="email" class="form-control" placeholder="Email">
                        <div class="input-group-append">
                            <div class="input-group-text"><span class="fas fa-envelope"></span></div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" placeholder="Password">
                        <div class="input-group-append">
                            <div class="input-group-text"><span class="fas fa-lock"></span></div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- AdminLTE -->
    <link rel="stylesheet" href="~/adminlte/plugins/fontawesome-free/css/all.min.css" />
    <link rel="stylesheet" href="~/adminlte/dist/css/adminlte.min.css" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - dotnet_mvc_first_app</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/dotnet_mvc_first_app.styles.css" asp-append-version="true" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">
                    dotnet_mvc_first_app
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Blog" asp-action="Index">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Profile" asp-action="Index">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - dotnet_mvc_first_app - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="~/adminlte/plugins/jquery/jquery.min.js"></script>
    <script src="~/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/adminlte/dist/js/adminlte.min.js"></script>

</body>
</html>

Views/Shared/_Navbar.cshtml
<nav class="main-header navbar navbar-expand navbar-dark bg-dark">
    <ul class="navbar-nav">
        <li class="nav-item"><a href="/" class="nav-link">Home</a></li>
        <li class="nav-item"><a href="/Dashboard" class="nav-link">Dashboard</a></li>
        <li class="nav-item"><a href="/Profile" class="nav-link">Profile</a></li>
    </ul>
</nav>